### ISSUE TITLE
E2E Framework V1

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#3357]
## E2E Framework 

- [ ] Port all test under `cmd/singularity` to `e2e`
- [ ] Remove `cmd/singularity` `*_test.go` files
- [ ] Re-config CI integrations (Travis/CircleCi) to use the new E2E framework

**Comment by cclerget** [comment]
We are far away from the initial goal. Closing.
