### ISSUE TITLE
Singularity v3.3.0-rc.1 Checklist

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3754]
This is the QA Checklist for Singularity v3.3.0-rc.1
Download: https://github.com/sylabs/singularity/releases/tag/v3.3.0-rc.1

Each comment should include:
* A description of the test done
* Some example output
* A link to an issue, if one was found

Each issue should include:
* The `Release 3.3.0` label

## Changed behaviors / defaults
- [x] `singularity remote login` will now use the default remote if one is not supplied
- [x] `singularity remote status` will now use the default remote if one is not supplied
- [x] `singularity pull` with the `shub` transport now caches the image
- [x] `singularity cache clean` will now delete only sub-directories of `SINGULARITY_CACHEDIR` instead of the directory itself

## New feature: `oras`
- [x] `singularity pull` understands a new transport, `oras`, which works with the Azure Container Registry and `docker/distribution`
- [x] `singularity push` understands a new transport, `oras`,  which works with the Azure Container Registry and `docker/distribution`

## New feature: `fakeroot`
- [x] `singularity build` understands a new option, `--fakeroot`
- [x] `singularity exec` understands a new option, `--fakeroot`
- [x] `singularity exec --network` accepts a new value of `fakeroot`
- [x] `singularity instance start` understands a new option, `--fakeroot`
- [x] `singularity instance start --network` accepts a new value of `fakeroot`
- [x] `singularity run` understands a new option, `--fakeroot`
- [x] `singularity run --network` accepts a new value of `fakeroot`
- [x] `singularity shell` understands a new option, `--fakeroot`
- [x] `singularity shell --network` accepts a new value of `fakeroot`
- [x] `singularity test` understands a new option, `--fakeroot`
- [x] `singularity test --network` accepts a new value of `fakeroot`

## New command: `sif`
- [x] `singularity sif` is a new command that allows you to work with SIF files.
- [x] `singularity sif add` Add a data object to a SIF file
- [x] `singularity sif del` Delete a specified object descriptor and data from SIF file
- [x] `singularity sif dump` Extract and output data objects from SIF files
- [x] `singularity sif header` Display SIF global headers
- [x] `singularity sif info` Display detailed information of object descriptors
- [x] `singularity sif list` List object descriptors from SIF files
- [x] `singularity sif new` Create a new empty SIF image file
- [ ] `singularity sif setprim` Set primary system partition

**Comment by sushma-4** [comment]
>singularity sif new Create a new empty SIF image file
```
sushma@Sushma-Ubuntu:~/test-3.3$ singularity sif new testsif.sif
sushma@Sushma-Ubuntu:~/test-3.3$ ls
testsif.sif
```

**Comment by sushma-4** [comment]
> singularity sif list List object descriptors from SIF files
```
sushma@Sushma-Ubuntu:~/syimg$ singularity sif list ubuntu.sif
Container id: 61a79e8d-8148-46bc-86e9-53156dff9e80
Created on:   2019-06-11 00:11:15 +0530 IST
Modified on:  2019-06-19 00:21:31 +0530 IST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33598               |Def.FILE
2    |1       |NONE    |36864-37273600            |FS (Squashfs/*System/amd64)
3    |1       |2       |37273600-37274555         |Signature (SHA384)
```

**Comment by sushma-4** [comment]
>singularity sif info Display detailed information of object descriptors
```
sushma@Sushma-Ubuntu:~/syimg$ singularity sif info 1 ubuntu.sif
Descr slot#: 0
  Datatype:  Def.FILE
  ID:        1
  Used:      true
  Groupid:   1
  Link:      NONE
  Fileoff:   32768
  Filelen:   830
  Ctime:     2019-06-11 00:11:15 +0530 IST
  Mtime:     2019-06-11 00:11:15 +0530 IST
  UID:       0
  Gid:       0
  Name:      .
```
Why is the Name just a `.`? Is is referring to the name of the container? Also,
A wrong ``descriptorid`` does not show any error, should this be an issue? @jscook2345 

```
sushma@Sushma-Ubuntu:~/syimg$ singularity sif info 4 ubuntu.sif
```

**Comment by sushma-4** [comment]
> singularity sif is a new command that allows you to work with SIF files.

Description:
  A set of commands are provided to display elements such as the SIF global 
  header, the data object descriptors and to dump data objects. **It is also 
  possible to modify a SIF file via this tool via the add/del commands.** 

I think this should be rewritten as - It is also possible to modify a SIF file via the add/del commands of this tool @jscook2345

**Comment by sushma-4** [comment]
> singularity sif header Display SIF global headers
```
sushma@Sushma-Ubuntu:~/syimg$ singularity sif header jupyter.sif
Launch:   #!/usr/bin/env run-singularity

Magic:    SIF_MAGIC
Version:  01
Arch:     amd64
ID:       d1b615f6-9200-4159-9ee6-9f00a1be3e1a
Ctime:    2018-12-20 16:05:16 +0530 IST
Mtime:    2018-12-20 16:05:16 +0530 IST
Dfree:    46
Dtotal:   48
Descoff:  4096
Descrlen: 27KB
Dataoff:  32768
Datalen:  2GB
```

The names of headers used here like Descoff, Descrlen should be expanded IMO, I  cant guess what they mean. @jscook2345

**Comment by sushma-4** [comment]
> singularity sif dump Extract and output data objects from SIF files

```
sushma@Sushma-Ubuntu:~/syimg$ singularity sif dump 1 cow.sif
from: ubuntu:16.04
bootstrap: library

%labels
	Author GodloveD

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%runscript
    fortune | cowsay | lolcat

%post
    apt-get -y update
    apt-get -y install fortune cowsay lolcat
```

**Comment by sushma-4** [comment]
> singularity sif del Delete a specified object descriptor and data from SIF file

```
sushma@Sushma-Ubuntu:~/syimg$ singularity sif list cow.sif
Container id: 8beeb080-2417-4efc-ae4e-b93856318d82
Created on:   2019-03-06 12:46:04 +0530 IST
Modified on:  2019-04-08 00:24:45 +0530 IST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33016               |Def.FILE
2    |1       |NONE    |36864-93917184            |FS (Squashfs/*System/amd64)
3    |1       |2       |93917184-93918139         |Signature (SHA384)
4    |NONE    |1   (G) |93921280-93922235         |Signature (SHA384)
sushma@Sushma-Ubuntu:~/syimg$ singularity sif del 4  cow.sif
sushma@Sushma-Ubuntu:~/syimg$ singularity sif list cow.sif
Container id: 8beeb080-2417-4efc-ae4e-b93856318d82
Created on:   2019-03-06 12:46:04 +0530 IST
Modified on:  2019-06-20 15:38:56 +0530 IST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33016               |Def.FILE
2    |1       |NONE    |36864-93917184            |FS (Squashfs/*System/amd64)
3    |1       |2       |93917184-93918139         |Signature (SHA384)
```

**Comment by sushma-4** [comment]
https://github.com/sylabs/singularity/issues/3767

No help for Singularity ORAS

**Comment by sushma-4** [comment]
> pull and push via ``oras``

**With local docker registry**
PUSH
```
sushma@Sushma-Ubuntu:~/syimg$ singularity push ubuntu.sif oras://localhost:5000/my-ubuntu
INFO:    No tag or digest found, using default: latest
WARN[0000] encountered unknown type appliciation/vnd.sylabs.sif.layer.tar; children may not be fetched 
WARN[0000] reference for unknown type: appliciation/vnd.sylabs.sif.layer.tar  digest="sha256:d7d0e0f5eeb6f14143a174b01c6c719d826cc7323ccff7a7f4d5c162e719aba7" mediatype=appliciation/vnd.sylabs.sif.layer.tar size=37274555
WARN[0000] encountered unknown type application/vnd.sylabs.sif.config.v1+json; children may not be fetched 
WARN[0000] reference for unknown type: application/vnd.sylabs.sif.config.v1+json  digest="sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" mediatype=application/vnd.sylabs.sif.config.v1+json size=0
sushma@Sushma-Ubuntu:~/syimg$ docker pull localhost:5000/my-ubuntu
Using default tag: latest
Error response from daemon: Encountered remote "application/vnd.sylabs.sif.config.v1+json"(unknown) when fetching
```
PULL
```
sushma@Sushma-Ubuntu:~/syimg$ singularity pull oras://localhost:5000/my-ubuntu
FATAL:   While pulling image from oci registry: failed to get checksum for //localhost:5000/my-ubuntu: while resolving reference: object required
```
**With ACR - tested by IanK**
PUSH
```
ian@T440s:test$ singularity push test.sif oras://iantest.azurecr.io/test/oras:newtest
WARN[0000] encountered unknown type appliciation/vnd.sylabs.sif.layer.tar; children may not be fetched 
WARN[0000] encountered unknown type application/vnd.sylabs.sif.config.v1+json; children may not be fetched 
WARN[0000] reference for unknown type: appliciation/vnd.sylabs.sif.layer.tar  digest="sha256:30c2d9b1cc51fc450f209d794f72bc84296fe91b581e4cbae563f72b9ae506ac" mediatype=appliciation/vnd.sylabs.sif.layer.tar size=25886720
WARN[0000] reference for unknown type: application/vnd.sylabs.sif.config.v1+json  digest="sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" mediatype=application/vnd.sylabs.sif.config.v1+json size=0
```
PULL
```
ian@T440s:test$ singularity pull pull.sif oras://iantest.azurecr.io/test/oras:newtest
INFO:    Downloading image with ORAS
INFO:    Pull complete: pull.sif
```
Encountering warnings and the pushes have been unsuccessful @jscook2345 

Update: So pulling and pushing was successful after some debugging! But it does not output that the image was pushed. There is small improvement we can make here, Not necessarily immediately however.

**Comment by sushma-4** [comment]
> singularity remote status will now use the default remote if one is not supplied
```
sushma@Sushma-Ubuntu:~/syimg$ singularity remote status 
INFO:    Checking status of default remote.
SERVICE           STATUS  VERSION
Builder Service   OK      v1.0.0-alpha.17-0-g1888cb7
Consent Service   OK      v1.0.0-alpha.9-0-ge826474
Keystore Service  OK      v1.7.0-0-g2aacf19
Library Service   OK      v1.0.0-alpha.23-0-g50362fb
Token Service     OK      v1.0.0-alpha.9-0-ge826474
```

**Comment by sushma-4** [comment]
> singularity remote login will now use the default remote if one is not supplied
```
sushma@Sushma-Ubuntu:~/syimg$ singularity remote login
INFO:    Authenticating with default remote.
Generate an API Key at https://cloud.sylabs.io/auth/tokens, and paste here:
API Key: 
INFO:    API Key Verified!
```

**Comment by sushma-4** [comment]
> singularity remote login will now use the default remote if one is not supplied
```
sushma@Sushma-Ubuntu:~/syimg$ singularity remote login
INFO:    Authenticating with default remote.
Generate an API Key at https://cloud.sylabs.io/auth/tokens, and paste here:
API Key: 
INFO:    API Key Verified!
```

**Comment by sushma-4** [comment]
> singularity pull with the shub transport now caches the image

Before:
```
sushma@Sushma-Ubuntu:~/.singularity$ cd cache
sushma@Sushma-Ubuntu:~/.singularity/cache$ ls
library  net  oci  oci-tmp
```
After:
```
sushma@Sushma-Ubuntu:~/.singularity$ cd cache
sushma@Sushma-Ubuntu:~/.singularity/cache$ ls
library  net  oci  oci-tmp  shub
```
Issue: When the download is incomplete, it would ask you to use an incomplete image from cache
```
sushma@Sushma-Ubuntu:~$ singularity pull shub://michael-tn/mpi-hello-world:latest
INFO:    Use image from cache
```
https://github.com/sylabs/singularity/issues/3776

**Comment by sushma-4** [comment]
> Other action commands with oras

```
sushma@Sushma-Ubuntu:~/syimg$ singularity run oras://localhost:5000/lolcow:latest
 _________________________________________
/ Even the clearest and most perfect      \
| circumstantial evidence is likely to be |
| at fault, after all, and therefore      |
| ought to be received with great         |
| caution. Take the case of any pencil,   |
| sharpened by any woman; if you have     |
| witnesses, you will find she did it     |
| with a knife; but if you take simply    |
| the aspect of the pencil, you will say  |
| that she did it with her teeth.         |
|                                         |
| -- Mark Twain, "Pudd'nhead Wilson's     |
\ Calendar"                               /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
sushma@Sushma-Ubuntu:~/syimg$ singularity exec oras://localhost:5000/lolcow:latest cowsay moo
 _____
< moo >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
sushma@Sushma-Ubuntu:~/syimg$ singularity shell oras://localhost:5000/lolcow:latest 
Singularity lolcow_latest.sif:~/syimg> cowsay moo
 _____
< moo >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
Singularity lolcow_latest.sif:~/syimg> exit
exit
sushma@Sushma-Ubuntu:~/syimg$ singularity instance start oras://localhost:5000/lolcow:latest myinstance
INFO:    instance started successfully
sushma@Sushma-Ubuntu:~/syimg$ singularity instance list
INSTANCE NAME    PID      IMAGE
myinstance       17737    /home/sushma/.singularity/cache/oras/sha256:d48dba1449488d24d270a20a9b9c6144b79ded5e4971195bfd0e36f507a9436d/lolcow_latest.sif
```

**Comment by sushma-4** [comment]
> singularity cache clean 
```
sushma@Sushma-Ubuntu:~$ singularity cache list 
NAME                     DATE CREATED           SIZE             TYPE
alpine_latest.sif        2019-06-25 00:31:54    2.72 MB          library

There 1 containers using: 2.72 MB, 0 oci blob file(s) using 0.00 kB of space.
Total space used: 2.72 MB
sushma@Sushma-Ubuntu:~$ singularity cache clean
sushma@Sushma-Ubuntu:~$ singularity cache list 
NAME                     DATE CREATED           SIZE             TYPE
alpine_latest.sif        2019-06-25 00:31:54    2.72 MB          library

There 1 containers using: 2.72 MB, 0 oci blob file(s) using 0.00 kB of space.
Total space used: 2.72 MB
```

Command inoperative

**Comment by sushma-4** [comment]
> Fakeroot 
>> singularity build
```
$ singularity build --fakeroot fr.sif lolcow.def
INFO:    Starting build...
INFO:    Running post scriptlet
INFO:    Adding labels
INFO:    Adding environment to container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete: fr.sif
```
>> singularity shell
```
sushma@Sushma-Ubuntu:~/syimg$ singularity shell --fakeroot lolcow.sif 
INFO:    Convert SIF file to sandbox...
Singularity lolcow.sif:~/syimg> cowsay moo
 _____
< moo >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
Singularity lolcow.sif:~/syimg> exit 
exit
INFO:    Cleaning up image...
```
>> singularity exec
```
sushma@Sushma-Ubuntu:~/syimg$ singularity exec --fakeroot lolcow.sif cowsay moo
INFO:    Convert SIF file to sandbox...
 _____
< moo >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
INFO:    Cleaning up image...
```
>> singularity run
```
sushma@Sushma-Ubuntu:~/syimg$ singularity run --fakeroot lolcow.sif 
INFO:    Convert SIF file to sandbox...
 _________________________________________
/ Q: How many Zen masters does it take to \
| screw in a light bulb? A: None. The     |
| Universe spins the bulb, and the Zen    |
| master stays out                        |
|                                         |
\ of the way.                             /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
INFO:    Cleaning up image...
```
>> singularity instance start
```
sushma@Sushma-Ubuntu:~/syimg$ singularity instance start --fakeroot lolcow.sif fri
INFO:    Convert SIF file to sandbox...
INFO:    instance started successfully
```
>> singularity test 
```
sushma@Sushma-Ubuntu:~/syimg$ singularity test --fakeroot frtest.sif
INFO:    Convert SIF file to sandbox...
WARNING: underlay of /etc/localtime required more than 50 (65) bind mounts
Hello from Test @$
INFO:    Cleaning up image...
```

**Issues:**
https://github.com/sylabs/singularity/issues/3753
https://github.com/sylabs/singularity/issues/3752

**Comment by sushma-4** [comment]
> singularity sif del
```
sushma@Sushma-Ubuntu:~/syimg$ singularity sif list ubuntu.sif 
Container id: 61a79e8d-8148-46bc-86e9-53156dff9e80
Created on:   2019-06-11 00:11:15 +0530 IST
Modified on:  2019-06-19 00:21:31 +0530 IST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33598               |Def.FILE
2    |1       |NONE    |36864-37273600            |FS (Squashfs/*System/amd64)
3    |1       |2       |37273600-37274555         |Signature (SHA384)
sushma@Sushma-Ubuntu:~/syimg$ singularity sif del 3 ubuntu.sif 
sushma@Sushma-Ubuntu:~/syimg$ singularity sif list ubuntu.sif 
Container id: 61a79e8d-8148-46bc-86e9-53156dff9e80
Created on:   2019-06-11 00:11:15 +0530 IST
Modified on:  2019-06-25 17:05:50 +0530 IST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
1    |1       |NONE    |32768-33598               |Def.FILE
2    |1       |NONE    |36864-37273600            |FS (Squashfs/*System/amd64)
```

**Comment by sushma-4** [comment]
> singularity shell --network accepts a new value of fakeroot
```
sushma@Sushma-Ubuntu:~/syimg$ singularity shell --network --fakeroot centos.sif
Singularity centos.sif:~/syimg> cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 
```
> exec
```
sushma@Sushma-Ubuntu:~/syimg$ singularity exec --network --fakeroot centos.sif cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 
```
> run
```
sushma@Sushma-Ubuntu:~/syimg$ singularity run --network --fakeroot lolcow.sif
 _________________________________________
/ Q: What do Winnie the Pooh and John the \
| Baptist have in common? A: The same     |
\ middle name.                            /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
> instance start
```
sushma@Sushma-Ubuntu:~/syimg$ singularity instance start --network --fakeroot frtest.sif fake
INFO:    instance started successfully
sushma@Sushma-Ubuntu:~/syimg$ singularity instance list 
INSTANCE NAME    PID      IMAGE
fake             7900     /home/sushma/syimg/frtest.sif
```
> test
```
sushma@Sushma-Ubuntu:~/syimg$ singularity test --network --fakeroot frtest.sif
Hello from Test @$
```

**Comment by jchavezlavalle** [comment]
Tried the following:
```sh
$ singularity sif new test.sif
$ ls
test.sif
$ singularity inspect -d test.sif
FATAL:   Unable to prossess command: exit status 255: 
```
opened a PR to fix this typo on inspect command on here -> https://github.com/sylabs/singularity/pull/3850

**Comment by jchavezlavalle** [comment]
On running:

```sh
$ singularity sif new test.sif
$ singularity sif list test.sif
Container id: 7e2b7187-19f1-469d-a4cb-01c24b2c60a5
Created on:   2019-07-02 17:10:26 +0200 CEST
Modified on:  2019-07-02 17:10:26 +0200 CEST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
$ singularity sif new test.sif
$ singularity sif list test.sif
Container id: 21eceefd-8ca9-4737-ba3d-02e5abbccc45
Created on:   2019-07-02 17:10:51 +0200 CEST
Modified on:  2019-07-02 17:10:51 +0200 CEST
----------------------------------------------------
Descriptor list:
ID   |GROUP   |LINK    |SIF POSITION (start-end)  |TYPE
------------------------------------------------------------------------------
```
It just overwrites the same sif file, shouldn't there be a verification first saying: "are you sure you want to overwrite? you already have a `test.sif` file in this directory"

**Comment by jchavezlavalle** [comment]
Considering test.def file to be the mongo db example we own as def file:

```sh
$ singularity sif new test.sif
$ singularity sif add --datatype 1 test.sif test.def
$ singularity inspect -d test.sif
$  FATAL:   Unable to process command: exit status 255: 
```
I cannot obtain a success message from the sif add command and therefore I assume this was successful, when running the inspect command to see the def file I get the error.
