### ISSUE TITLE
Port e2e tests to use singularity execution context

### ISSUE THREAD

**Issue by cclerget** [apptainer/singularity#3828]
Port following tests to use singularity execution context (https://github.com/sylabs/singularity/blob/master/e2e/internal/e2e/singularitycmd.go) :

- [x] docker -> https://github.com/sylabs/singularity/blob/master/e2e/docker/docker.go
- [x] env -> https://github.com/sylabs/singularity/blob/master/e2e/env/env.go
- [x] help -> https://github.com/sylabs/singularity/blob/master/e2e/help/help.go
- [x] imgbuild -> https://github.com/sylabs/singularity/blob/master/e2e/imgbuild/imgbuild.go
- [x] instance -> https://github.com/sylabs/singularity/blob/master/e2e/instance/instance.go
- [x] pull -> https://github.com/sylabs/singularity/blob/master/e2e/pull/pull.go
- [x] push -> https://github.com/sylabs/singularity/blob/master/e2e/push/push.go
- [x] remote -> https://github.com/sylabs/singularity/blob/master/e2e/remote/remote.go
- [x] version -> https://github.com/sylabs/singularity/blob/master/e2e/version/version.go
- [x] inspect -> https://github.com/sylabs/singularity/blob/master/e2e/inspect/inspect.go
