### ISSUE TITLE
3.4.2 Merge Checklist

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4557]
PRs that need to be merged / cherry-picked from master into the release-3.4 branch:

 - [x] #4522 Set workable permissions on OCI -> sandbox rootless builds (targets release-3.4 directly)
 - [x] #4540 Fallback correctly to user namespace for non setuid installation (targets release-3.4 directly)
 - [x] #4434 build_runtime_suid.mk (cherry pick from master) (via #4566)
 - [x] #4436 Fix chmod makefile error at install step (cherry pick from master) (via #4566)
 - [x] #4523 Create CACHEDIR if it doesn't exist (via #4572)

**Comment by dtrudg** [comment]
All features were merged and the release was made
