### ISSUE TITLE
Cherry-picks for 3.5.1-rc.1

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4779]
Tracking PRs that wll be cherry-picked to `release-3.5` for the upcoming `3.5.1` bugfix release.

- [x] #4737 Fix disk space leak when building from docker-archive - picked in #4787 
- [x] #4720 Override SIGABRT Go handler - picked in #4788
- [x] #4743 Wrap inspect command around singularity exec - picked in #4791 
- [x] #4796 Hotfix for 2860 - All files in container owned by root - picked in #4798

*Group of build related fixes* - picked in #4790
- [x] #4745 Ensure raw definition creates correct header
- [x] #4752 Set default umask during stages build
- [x] #4777 Use temporary file to execute build script section

*Group underlay / symlink issues* - picked in #4786 
 - [x] #4759 Fix underlay/override directory issue
 - [x] #4770 Fix current working directory symlink issue

*Group container restrictions* - picked in #4784
- [x] #4761 Add allow container encrypted directive
- [x] #4773 Check all partitions for image type check 

*Group of BTRFS fixes* - picked in #4782 
- [x] #4754 Fix wrong st_dev/mountinfo for btrfs filesystem
- [x] #4766 Fix index shift during optional fields parsing in parseMountInfoLine

*Group of arch fixes* - picked in #4781 
- [x] #4693 Fix missing STKFLT signal for mips 
- [x] #4742 Fix F_SETLK64 bad value on ppc64 arch with fcntl syscall
- [x] #4753 Fix x86/arm/mips 32 bits system compilation error
- [x] #4772 Fix setLk build error ... again
