### ISSUE TITLE
Cherry picks for 3.5.2

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4841]
- [x] #4833 Fakeroot build and missing seccomp support (picked in #4845)
 - [x] #4838 Fix useless error when an element of the current working directory is a symlink (picked in #4846)
 - [x] #4839 Fix fakeroot sandbox build chown error on Lustre/GPFS etc. (picked in #4847)
 - [x] #4840 Fix fakeroot build issue due to section script location (picked in #4848)
 - [x] #4850 net cache issue (picked in #4852)
