### ISSUE TITLE
3.5.3 Cherry Picks

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#4965]
Tracking for fixes for a 3.5.3 bugfix release.

**Travis** Cherry-pick PR #5011
- [x] #5008 Fix travis Go install dependencies 

**GPU** Cherry-pick PR #5009 
- [x] #4990 - Update `nvliblist.conf` with the new cuda 10.2 libs
- [x] #4946 - Fix nvidia persitenced socket bind mount error with --writable

**Specific filesystem fixes** PR #5010
- [x] #4922 - Add ceph to filesystems needing st_dev workaround
- [x] #4938 - Embed action scripts in runtime and create them on-the-fly (note... behavior change, but necessary for CRAY CLE compatibility. Needs consideration).

**Deps / Packaging / Install** PR #5012 
- [x] #4890 - Updated to sif 1.0.9, and remove unnecessary function 
- [x] #4942 - Fix setgid group inheritance during make install 
- [x] #4978 - Fix broken links and tidy README.md 

**Image building** PR #5013
- [x] #4873 - Do not follow symlinks while copying between stages
- [x] #4958 - Ensure build rootPath has owner write permission 
- [x] #4972 - Fix build post/test -c section parameter regression
- [x] #4973 - Fix build post section issue /etc/resolv.conf and/or /etc/hosts are missing

**Runtime** PR #5014
- [x] #4888 - Return current UID instead of error in namespaces.HostUID
- [x] #4935 - Fix a logic error with sandbox image and all layers disabled
- [x] #4974 - Add CAP_SYS_ADMIN check for root user and user namespace fallback

**Sylabs Cloud** PR #5015
- [x] #4977 - Allow 0x or non-prefixed key IDs/fingerprints

**Test fixes exposed in PRO 3.5 release work-up**

These fixes add the config command tests, and will allow tests to run across more distros without failing, which is likely to be beneficial when troubleshooting distro specific things. Most of them don't affect the CI running tests on Ubuntu.

- [x] https://github.com/sylabs/singularity/pull/4916 - Fix e2e config test with grep match
- [x] https://github.com/sylabs/singularity/pull/4914 - AllowSetuid no test requires user namespace to succeed
- [x] https://github.com/sylabs/singularity/pull/4912 - Call require.Network correctly in e2e ACTIONS/network
- [x] https://github.com/sylabs/singularity/pull/4910 - Fix e2e security capabilities regular expression match on old kernels
- [x] https://github.com/sylabs/singularity/pull/4909 - Protect additional e2e tests needing UserNS, overlay with require.xxx
- [x] https://github.com/sylabs/singularity/pull/4908 - Use img instead of docker to run e2e tests registry on RHEL 6 
- [x] https://github.com/sylabs/singularity/pull/4902 - Fixed OS versions/kernel req in TestDockerDefFile & e2e
- [x] https://github.com/sylabs/singularity/pull/4900 - Skip testPersistentOverlay if no overlay support
- [x] https://github.com/sylabs/singularity/pull/4898 - Fix network_linux_test where bridge not available / setup fails on RHEL6
- [x] https://github.com/sylabs/singularity/pull/4895 - Correct nc args to fix TestAddDelNetworks with OpenBSD nc
- [x] https://github.com/sylabs/singularity/pull/4889 - Avoid use of overlay when not available in mount and oci bundle tests
- [x] https://github.com/sylabs/singularity/pull/4888 - Return current UID instead of error in namespaces.HostUID
- [x] https://github.com/sylabs/singularity/pull/4884 - Check for userns availability in actions_test.go
- [x] https://github.com/sylabs/singularity/pull/4760 - Add e2e tests for various configuration directives

*Additional* 

 - [x] Fix instance join for instances started with --boot #5034

**Comment by dtrudg** [comment]
All cherry-picks are done for 3.5.3-rc.1
