### ISSUE TITLE
3.6.3 cherry-picks

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5563]
Setting up a list of cherry-picks to be ongoing toward 3.6.3, as `master` has moved ahead with the runtime config handling changes that we might not want to backport due to their scope.

- [x] Add CAP_MKNOD in capability bounding set of RPC #5548
- [x] Fix decryption issue when using both IPC and PID namespaces #5549
- [x] Fix unsupported builtins panic from shell interpreter and add umask support #5550
- [x] fix: Do not load keyring in prepare_linux if ECL not enabled #5562
- [x] Ensure sandbox option overrides remote build dst #5568
