### ISSUE TITLE
Singularity docs sections updating

### ISSUE THREAD

**Issue by pedroalvesbatista** [apptainer/singularity#6034]
### Version of Singularity:

`3.8` - but documentation has some references to `3.7`

### Expected behavior

References pointing to `3.8`.
Decide about Sylabs Cloud and SingularityPRO references on links and docs as general.

### Actual behavior

References pointing to `3.7`.

### TODO :
- [ ] Review all references pointing to not open source solutions
- [ ] Review all references pointing to Sylabs Cloud
- [ ] Double-check all other parts from sections regarding up-to-date references
- [ ] Check if any section conflicts with bug-fixes and updates

**Comment by DrDaveD** [comment]
Sylabs Cloud is still relevant.  I don’t think we need to remove references to SingularityPRO now, maybe we will later.  More important is the URLs pointing to the Sylabs website, and possibly email addresses if there are any.  I don’t see any references to 3.7 in URLs in the source code.  Look through the source code, not the website.  Some of those URLs are generated.

The source code is in https://github.com/hpcng/singularity-userdocs and https://github.com/hpcng/singularity-admindocs

**Comment by pedroalvesbatista** [comment]
As we have solved those points, will close this issue.
